name: End-to-end tests
on:
  push:
    branches:
      - split
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    # run 10 copies of the current job in parallel
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run split Cypress tests 🧪
        uses: cypress-io/github-action@v6
        # pass the machine index and the total number
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
